bloatware=(
    "gnome-games"
    "gnome-weather"
    "gnome-maps"
    "gnome-calculator"
    "evolution"
    "gnome-characters"
    "gnome-chess"
    "gnome-clocks"
    "gnome-contacts"
    "gnome-extensions"
    "gnome-mahjongg"
    "gnome-mines"
    "gnome-music"
    "gnome-sudoku"
    "transmission-gtk"
    "transmission"
    "sushi"
    "libreoffice"
    "gimp"
    "totem"
    "simple-scan"
    "polari"
    "quadrapassel"
    "swell-foop"
    "lightsoff"
    "system-config-printer"
    "cups"
    "dconf-editor"
    "MozillaFirefox"
    "MozillaFirefox-branding-openSUSE"
    "lftp"

)

sudo zypper rm -u "${bloatware[@]}"
sudo zypper al "${bloatware[@]}"
